from .combinatons import generate_combo as generate_combo, hex_chars as hex_chars
from chepy import Chepy as Chepy
from typing import Dict, Iterator

def factordb(n: int) -> dict: ...
def construct_private_key(n: int, e: int, d: int, format: str=..., passphrase: str=...) -> str: ...
def xor_bruteforce_multi(data: str, min: int=..., max: int=..., errors: str=...) -> Iterator[Dict[str, str]]: ...
