from typing import Dict, Iterator, Union

def factordb(n: int) -> dict: ...
def construct_private_key(n: int, e: int, d: int, format: str=..., passphrase: str=...) -> str: ...
def xor_bruteforce_multi(data: str, min: int=..., max: int=..., errors: str=...) -> Iterator[Dict[str, str]]: ...
def xor_key_from_files(f1_path:str, f2_path: str, min: int =..., max: int = ...) -> Union[bytes, None]: ...
