dist: bionic
language: python
python:
- '3.7'
cache:
- pip
addons:
  sonarcloud:
    organization: "securisec"
    token:
      secure: SB1eaFai/4thp6R41DxSjuPquXxVTE5TKUFIIpA9kHjflUDDHwL9BdB3Wp9m9XpxUmRLlUQglhMx2JodM9zqAO6zBO7g+E0vHsfbhD8nf6oR0yJb3dAnd5TrBiYENxY4Mmg1JxehfYm4ifgxghUMT8rS3rBuSjwLfgB+nyuB0TVf9TTqOsFnSNv2nlU4pcT+bxCkgRBMsHLUcii67P01eH0H0sA29esm+oyDITHrtX/AuKkKcAubg9hlnzm8PuOS8+H8wOTmJlmUu9jwCoeNvEyxqEE8F352KKrcGdm7Lr+nod2KVbcfl0qL1CMPFBqAj6arQ3lK4JSdkKXQnLedZH887GSAw9qIroVvRnyUFVJoKOYq1uwBO1AawjiDH5QE3Vny4RQMBc+3iJQNYy9Rm0wWGorn4BaUfbev4K++wMeh5kPHyPZO22/wd0RHXsra4r6FmqqocQ1a/vgShRalLeWvZDAUP2cIzovXTYRFGS+Or671tnTh4rrAT7jMXiBHZdIFIP0ZtV4s0zAbDkVh0T79wfIW9B0EVxWVQ+4bO6EUClG5L6HeHjH6dbl72v82xZVcmMrA5EIF7HfixWYL+CeAQIBAMrXweztzjIlWwbn76fZPFVCNmMfTBzR6xWUaGYt+EM7RPfo0xIqVEfmSeJ6vPKQx/jA6g0EOKCyaoHY=
before_install:
- python -V
- pip -V
- pip install pytest pytest-cov bandit sphinx recommonmark
- pip install -e .
script:
- pytest --disable-pytest-warnings --cov-report=xml --cov=chepy --cov-config=.coveragerc
  tests/
- coverage report -m
- sed -i 's/enableplugins = false/enableplugins = true/' ~/.chepy/chepy.conf
- sed -i '/chepy/d' chepy/chepy_plugins/requirements.txt
- pip install -r chepy/chepy_plugins/requirements.txt
- pytest --disable-pytest-warnings tests_plugins/
- python -c "from chepy import Chepy"
- bandit --recursive chepy/ --ignore-nosec --skip B101,B413,B303,B310,B112,B304,B320,B410,B404 --output .bandit.json --format json
- make -C docs/ clean html
- sonar-scanner
deploy:
  provider: pypi
  user: __token__
  password:
    secure: uhLPkQibP8u6mnTBq8tz8vx72FEse1rBCKiT0FAXWXOvmcdYEPRtFGQAjxFRemYHIpoYz3lK1MY9c0DRmz0vzkV+62FIQsLclzaHQH2XBf2mjpsNpGzvk4eXq5aNc003BH0n3UKuOJg9qJcBmqNh8k0QIY/lnFIGUDQzhtnplbCJHB7Cue8S8vuDgMZTj2I6l3obnYWv47jgcYqVBfJXYzIfJV+WX+n0coYbKlleiNlMZf7hwrMkNSnwoGUO04XHzIfPQ0TNSZNT7N/EShi77rYT+saY//X+0ydv/2NZ6izCg9gvZqNYRRBDmBBN0to/YTjDvtqt4eYKNPgscP65xD8dWZW2Kseg6CC6lJKwd0Mq65NPtLH+vwGt4Neg9eGxb6t2Wz2KN3DlUfhOnCDhumwD6nc8VwQuTzGZvsARPJ0uzHzi/b5dBD/+YguZjnLR2cmKBdq6YcQ1M8J1cmZvGl79I/IrjMkRBngcoCusJCKx2SyXtBMQYwFphEQb4dh8lL+NfmPGRP3rwMbZbzJTFQrJ9JcA1+tw7obVE6HKjuod9zbSBS2RfMOrHotckh8NNeP/6tdTf69wj+JcOkryl16uld+5pk3RObUcf+9jZ9RHE64xAE3+xBMnl0+/Plb3fBQ+tKuG2LsuV89hMF08R1yMYReiRGVyHMxrRrusdcU=
  on:
    tags: true
  skip_existing: true
  skip_cleanup: true
