from typing import Any, Dict

class Encoding:
    py_encodings: Any = ...
    py_text_encodings: Any = ...
    asciichars: Any = ...
    brailles: Any = ...
    NATO_CONSTANTS_DICT: Dict[str, str] = ...

class EncryptionConsts:
    MORSE_CODE_DICT: Any = ...

class PcapUSB:
    qwerty_map: Any = ...
    qwerty_modifier: Any = ...
    dvorak: Any = ...
    dvorak_modifier: Any = ...
