from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from .exceptions import StateNotList as StateNotList
from typing import Any

class AritmeticLogic(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def str_bit_shift_right(self, amount: int) -> Any: ...
    def add(self, n: int) -> Any: ...
    def subtract(self, n: int) -> Any: ...
    def multiply(self, n: int) -> Any: ...
    def divide(self, n: int) -> Any: ...
    def power(self, n: int) -> Any: ...
    def sum(self): ...
    def mean(self): ...
    def median(self): ...
