from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from typing import Any, TypeVar

pydash: Any
CodeTidyT = TypeVar('CodeTidyT', bound='CodeTidy')

class CodeTidy(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def minify_json(self) -> CodeTidyT: ...
    def beautify_json(self, indent: int=...) -> CodeTidyT: ...
    def minify_xml(self) -> CodeTidyT: ...
    def beautify_xml(self) -> CodeTidyT: ...
    def php_deserialize(self) -> CodeTidyT: ...
    def to_upper_case(self, by: str=...) -> CodeTidyT: ...
    def to_lower_case(self) -> CodeTidyT: ...
    def to_snake_case(self) -> CodeTidyT: ...
    def to_camel_case(self, ignore_space: bool=...) -> CodeTidyT: ...
    def to_kebab_case(self) -> CodeTidyT: ...
    def swap_case(self) -> CodeTidyT: ...
    def to_leetspeak(self, special_chars: bool=...) -> CodeTidyT: ...
