from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from typing import Any

pydash: Any

class CodeTidy(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def minify_json(self): ...
    def beautify_json(self, indent: int=...) -> Any: ...
    def minify_xml(self): ...
    def beautify_xml(self): ...
    def php_deserialize(self): ...
    def to_upper_case(self, by: str=...) -> Any: ...
    def to_lower_case(self): ...
    def to_snake_case(self): ...
    def to_camel_case(self, ignore_space: bool=...) -> Any: ...
    def to_kebab_case(self): ...
    def swap_case(self): ...
    def to_leetspeak(self, special_chars: bool=...) -> Any: ...
