from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from typing import Any

class Compression(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def fix_zip_header(self): ...
    def zip_info(self): ...
    def zip_list_files(self): ...
    def unzip_one(self, file: str, password: str=...) -> Any: ...
    def unzip_all(self, password: str=...) -> Any: ...
    def create_zip_file(self, file_name: str) -> Any: ...
    def tar_list_files(self, mode: str=...) -> Any: ...
    def tar_extract_one(self, filename: str, mode: str=...) -> Any: ...
    def tar_extract_all(self, mode: str=...) -> Any: ...
    def tar_compress(self, filename: str, mode: str=...) -> Any: ...
    def gzip_compress(self, file_name: str=...) -> Any: ...
    def gzip_decompress(self): ...
    def bzip_compress(self): ...
    def bzip_decompress(self): ...
    def zlib_compress(self, level: int=...) -> Any: ...
    def zlib_decompress(self): ...
    def lzma_compress(self): ...
    def lzma_decompress(self): ...
    def raw_inflate(self): ...
    def raw_deflate(self): ...
