from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from chepy.modules.internal.constants import Encoding as Encoding
from typing import Any, TypeVar, Union

yaml: Any
DataFormatT = TypeVar('DataFormatT', bound='DataFormat')

class DataFormat(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def eval_state(self) -> DataFormatT: ...
    def bytes_to_ascii(self) -> DataFormatT: ...
    def list_to_str(self, join_by: Union[str, bytes]=...) -> DataFormatT: ...
    def str_list_to_list(self) -> DataFormatT: ...
    def join_list(self, by: Union[str, bytes]=...) -> DataFormatT: ...
    def json_to_dict(self) -> DataFormatT: ...
    def dict_to_json(self) -> DataFormatT: ...
    def yaml_to_json(self) -> DataFormatT: ...
    def json_to_yaml(self) -> DataFormatT: ...
    def base58_encode(self) -> DataFormatT: ...
    def base58_decode(self) -> DataFormatT: ...
    def base85_encode(self) -> DataFormatT: ...
    def base85_decode(self) -> DataFormatT: ...
    def base16_encode(self) -> DataFormatT: ...
    def base16_decode(self) -> DataFormatT: ...
    def base32_encode(self) -> DataFormatT: ...
    def base32_decode(self) -> DataFormatT: ...
    def to_int(self) -> DataFormatT: ...
    def to_bytes(self) -> DataFormatT: ...
    def from_bytes(self) -> DataFormatT: ...
    def base64_encode(self, custom: str=...) -> DataFormatT: ...
    def base64_decode(self, custom: str=..., fix_padding: bool=...) -> DataFormatT: ...
    def decode_bytes(self, errors: str=...) -> DataFormatT: ...
    def to_hex(self) -> DataFormatT: ...
    def from_hex(self) -> DataFormatT: ...
    def hex_to_int(self) -> DataFormatT: ...
    def hex_to_binary(self) -> DataFormatT: ...
    def hex_to_str(self, ignore: bool=...) -> DataFormatT: ...
    def str_to_hex(self) -> DataFormatT: ...
    def int_to_hex(self) -> DataFormatT: ...
    def int_to_str(self) -> DataFormatT: ...
    def binary_to_hex(self) -> DataFormatT: ...
    def normalize_hex(self, is_bytearray: Any=...) -> DataFormatT: ...
    def str_from_hexdump(self) -> DataFormatT: ...
    def to_hexdump(self) -> DataFormatT: ...
    def from_hexdump(self) -> DataFormatT: ...
    def url_encode(self, safe: str=...) -> DataFormatT: ...
    def url_decode(self) -> DataFormatT: ...
    def bytearray_to_str(self, encoding: str=..., errors: str=...) -> DataFormatT: ...
    def str_to_list(self) -> DataFormatT: ...
    def str_to_dict(self) -> DataFormatT: ...
    def to_charcode(self, escape_char: str=...) -> DataFormatT: ...
    def from_charcode(self, prefix: str=...) -> DataFormatT: ...
    def to_decimal(self) -> DataFormatT: ...
    def from_decimal(self) -> DataFormatT: ...
    def to_binary(self) -> DataFormatT: ...
    def from_binary(self) -> DataFormatT: ...
    def to_octal(self) -> DataFormatT: ...
    def from_octal(self) -> DataFormatT: ...
    def to_html_entity(self) -> DataFormatT: ...
    def from_html_entity(self) -> DataFormatT: ...
    def to_punycode(self) -> DataFormatT: ...
    def from_punycode(self) -> DataFormatT: ...
    def encode_bruteforce(self) -> DataFormatT: ...
    def decode_bruteforce(self) -> DataFormatT: ...
    def to_braille(self) -> DataFormatT: ...
    def from_braille(self) -> DataFormatT: ...
    def trim(self) -> DataFormatT: ...
