from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from typing import Any, TypeVar

DateTimeT = TypeVar('DateTimeT', bound='DateTime')

class DateTime(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def from_unix_ts(self) -> DateTimeT: ...
    def to_unix_ts(self) -> DateTimeT: ...
