from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from typing import Any

parsel: Any

class Extractors(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def extract_hashes(self): ...
    def extract_strings(self, length: int=...) -> Any: ...
    def extract_ips(self, invalid: bool=..., is_binary: bool=...) -> Any: ...
    def extract_email(self, is_binary: bool=...) -> Any: ...
    def extract_mac_address(self, is_binary: bool=...) -> Any: ...
    def extract_urls(self, is_binary: bool=...) -> Any: ...
    def extract_domains(self, is_binary: bool=...) -> Any: ...
    def xpath_selector(self, query: str, namespaces: str=...) -> Any: ...
    def css_selector(self, query: str) -> Any: ...
    def jpath_selector(self, query: str) -> Any: ...
    def html_comments(self): ...
    def javascript_comments(self): ...
    def html_tags(self, tag: str) -> Any: ...
    def extract_google_api(self): ...
    def extract_google_captcha(self): ...
    def extract_google_oauth(self): ...
    def extract_aws_keyid(self): ...
    def extract_aws_s3_url(self): ...
    def extract_facebook_access_token(self): ...
    def extract_auth_basic(self): ...
    def extract_auth_bearer(self): ...
    def extract_mailgun_api(self): ...
    def extract_twilio_api(self): ...
    def extract_twilio_sid(self): ...
    def extract_paypal_bt(self): ...
    def extract_square_oauth(self): ...
    def extract_square_access(self): ...
    def extract_stripe_api(self): ...
    def extract_github(self): ...
    def extract_rsa_private(self): ...
    def extract_dsa_private(self): ...
    def extract_jwt_token(self): ...
    def extract_base64(self, min: int=...) -> Any: ...
