from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from typing import Any, TypeVar

LanguageT = TypeVar('LanguageT', bound='Language')

class Language(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def unicode_chrs_by_lang(self, lang: str) -> LanguageT: ...
    def find_emojis(self) -> LanguageT: ...
    def encode_utf_16_le(self) -> LanguageT: ...
    def decode_utf_16_le(self) -> LanguageT: ...
    def encode_utf_16_be(self) -> LanguageT: ...
    def decode_utf_16_be(self) -> LanguageT: ...
    def encode_utf_7(self) -> LanguageT: ...
    def decode_utf_7(self) -> LanguageT: ...
    def encode_cp500(self) -> LanguageT: ...
    def decode_cp500(self) -> LanguageT: ...
    def encode_cp037(self) -> LanguageT: ...
    def decode_cp037(self) -> LanguageT: ...
    def encode_cp874(self) -> LanguageT: ...
    def decode_cp874(self) -> LanguageT: ...
    def encode_cp932(self) -> LanguageT: ...
    def decode_cp932(self) -> LanguageT: ...
    def encode_gbk(self) -> LanguageT: ...
    def decode_gbk(self) -> LanguageT: ...
    def encode_gb2312(self) -> LanguageT: ...
    def decode_gb2312(self) -> LanguageT: ...
    def encode_cp949(self) -> LanguageT: ...
    def decode_cp949(self) -> LanguageT: ...
    def encode_cp950(self) -> LanguageT: ...
    def decode_cp950(self) -> LanguageT: ...
    def encode_cp1250(self) -> LanguageT: ...
    def decode_cp1250(self) -> LanguageT: ...
    def encode_cp1251(self) -> LanguageT: ...
    def decode_cp1251(self) -> LanguageT: ...
    def encode_cp1252(self) -> LanguageT: ...
    def decode_cp1252(self) -> LanguageT: ...
    def encode_cp1253(self) -> LanguageT: ...
    def decode_cp1253(self) -> LanguageT: ...
    def encode_cp1254(self) -> LanguageT: ...
    def decode_cp1254(self) -> LanguageT: ...
    def encode_cp1255(self) -> LanguageT: ...
    def decode_cp1255(self) -> LanguageT: ...
    def encode_cp1256(self) -> LanguageT: ...
    def decode_cp1256(self) -> LanguageT: ...
    def encode_cp1257(self) -> LanguageT: ...
    def decode_cp1257(self) -> LanguageT: ...
    def encode_cp1258(self) -> LanguageT: ...
    def decode_cp1258(self) -> LanguageT: ...
    def encode_iso8859_2(self) -> LanguageT: ...
    def decode_iso8859_2(self) -> LanguageT: ...
    def encode_iso8859_3(self) -> LanguageT: ...
    def decode_iso8859_3(self) -> LanguageT: ...
    def encode_iso8859_4(self) -> LanguageT: ...
    def decode_iso8859_4(self) -> LanguageT: ...
    def encode_iso8859_5(self) -> LanguageT: ...
    def decode_iso8859_5(self) -> LanguageT: ...
    def encode_iso8859_6(self) -> LanguageT: ...
    def decode_iso8859_6(self) -> LanguageT: ...
    def encode_iso8859_7(self) -> LanguageT: ...
    def decode_iso8859_7(self) -> LanguageT: ...
    def encode_iso8859_8(self) -> LanguageT: ...
    def decode_iso8859_8(self) -> LanguageT: ...
    def encode_iso8859_9(self) -> LanguageT: ...
    def decode_iso8859_9(self) -> LanguageT: ...
    def encode_iso8859_10(self) -> LanguageT: ...
    def decode_iso8859_10(self) -> LanguageT: ...
    def encode_iso8859_11(self) -> LanguageT: ...
    def decode_iso8859_11(self) -> LanguageT: ...
    def encode_iso8859_13(self) -> LanguageT: ...
    def decode_iso8859_13(self) -> LanguageT: ...
    def encode_iso8859_14(self) -> LanguageT: ...
    def decode_iso8859_14(self) -> LanguageT: ...
    def encode_iso8859_15(self) -> LanguageT: ...
    def decode_iso8859_15(self) -> LanguageT: ...
    def remove_diacritics(self) -> LanguageT: ...
    def unicode_to_str(self) -> LanguageT: ...
