from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from typing import Any, TypeVar

NetworkingT = TypeVar('NetworkingT', bound='Networking')

class Networking(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def defang_url(self) -> NetworkingT: ...
    def refang_url(self) -> NetworkingT: ...
    def defang_ip(self) -> NetworkingT: ...
    def refang_ip(self) -> NetworkingT: ...
    def parse_uri(self) -> NetworkingT: ...
    def parse_ip_range(self) -> NetworkingT: ...
    def parse_ipv6(self) -> NetworkingT: ...
    def get_ssl_cert(self, port: int=...) -> NetworkingT: ...
