from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from typing import Any

class Networking(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def defang_url(self): ...
    def refang_url(self): ...
    def defang_ip(self): ...
    def refang_ip(self): ...
    def parse_uri(self): ...
    def parse_ip_range(self): ...
    def parse_ipv6(self): ...
    def get_ssl_cert(self, port: int=...) -> Any: ...
