from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from typing import Any, TypeVar

OtherT = TypeVar('OtherT', bound='Other')

class Other(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def generate_uuid(self) -> OtherT: ...
