from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from typing import Any, TypeVar

SearchT = TypeVar('SearchT', bound='Search')

class Search(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def search(self, pattern: str) -> SearchT: ...
    def search_ctf_flags(self, prefix: str, postfix: str=...) -> SearchT: ...
    def search_slack_tokens(self) -> SearchT: ...
    def search_slack_webhook(self) -> SearchT: ...
    def search_private_key(self) -> SearchT: ...
    def search_twilio_key(self) -> SearchT: ...
    def search_aws_key(self) -> SearchT: ...
