from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from typing import Any

class Search(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def search(self, pattern: str) -> Any: ...
    def search_ctf_flags(self, prefix: str, postfix: str=...) -> Any: ...
    def search_slack_tokens(self): ...
    def search_slack_webhook(self): ...
    def search_private_key(self): ...
    def search_twilio_key(self): ...
    def search_aws_key(self): ...
