from ..core import ChepyCore as ChepyCore, ChepyDecorators as ChepyDecorators
from .exceptions import StateNotDict as StateNotDict, StateNotList as StateNotList
from typing import Any, Union

class Utils(ChepyCore):
    def __init__(self, *data: Any) -> None: ...
    state: Any = ...
    def reverse(self, count: int=...) -> Any: ...
    def count_occurances(self, regex: str, case_sensitive: bool=...) -> Any: ...
    def remove_whitespace(self, spaces: bool=..., carriage_return: bool=..., line_feeds: bool=..., tabs: bool=..., form_feeds: bool=...) -> Any: ...
    def remove_nullbytes(self): ...
    def regex_search(self, pattern: str, ignore_case: bool=..., multiline: bool=..., dotall: bool=..., unicode: bool=..., extended: bool=...) -> Any: ...
    def split_by(self, pattern: str=..., trim: Any=...) -> Any: ...
    def split_by_n(self, n: int) -> Any: ...
    def select_every_n(self, n: int, start: int=...) -> Any: ...
    def unique(self): ...
    def sort_list(self, reverse: bool=...) -> Any: ...
    def sort_dict_key(self, reverse: bool=...) -> Any: ...
    def sort_dict_value(self, reverse: bool = ...): ...
    def filter_list(self, by: Union[str, dict], regex: bool=...) -> Any: ...
    def filter_list_by_length(self, length: int, exact: bool=...) -> Any: ...
    def filter_dict_key(self, by: str) -> Any: ...
    def filter_dict_value(self, by: str) -> Any: ...
    def slice(self, start: int=..., end: int=...) -> Any: ...
    def find_replace(self, pattern: str, repl: str, ignore_case: Any=...) -> Any: ...
    def escape_string(self): ...
    def unescape_string(self): ...
    def color_hex_to_rgb(self): ...
    def diff(self, state: int=..., buffer: int=..., colors: bool=..., swap: bool=...) -> Any: ...
    def pad(self, width: int, direction: str=..., char: str=...) -> Any: ...
    def count(self): ...
    def set(self): ...
    def regex_to_str(self, all_combo: bool=...) -> Any: ...
